id: P6C9744A3
initial_creation_type: ocr
source_metadata:
  volumes:
    f5420a938d6a463aa552b95a0a810151:
      base_file: v027.txt
      image_group_id: I1PD95872
      title: དཱི་པཾ་ཀཱ་ར་ཤྲཱི་ཛྙཱ་ནའི་ཆོས་ཀྱི་གླུ།
      total_pages: 1953
      volume_number: 27
